"use client";

import { useMemo } from "react";
import Sidebar from "@/components/Sidebar";
import { useSystemStore } from "@/store/useSystemStore";
import { FiDownload, FiFileText } from "react-icons/fi";
import jsPDF from "jspdf";

export default function SummaryPage() {
  const {
    systemName,
    nodes,
    edges,
  } = useSystemStore();

  const summary = useMemo(() => {
    let content = `# ${systemName}\n\n`;

    content += `## System Overview\n\n`;
    content += `This document outlines the system design for **${systemName}**.\n\n`;

    if (nodes.length > 0) {
      content += `## Architecture Components\n\n`;
      nodes.forEach((node) => {
        content += `- ${node.data.label}\n`;
      });
      content += `\n`;
    }

    if (edges.length > 0) {
      content += `## Component Connections\n\n`;
      edges.forEach((edge) => {
        const sourceNode = nodes.find((n) => n.id === edge.source);
        const targetNode = nodes.find((n) => n.id === edge.target);
        if (sourceNode && targetNode) {
          content += `- ${sourceNode.data.label} → ${targetNode.data.label}\n`;
        }
      });
      content += `\n`;
    }

    content += `---\n\n`;
    content += `*Generated by System Design Helper*\n`;

    return content;
  }, [
    systemName,
    nodes,
    edges,
  ]);

  const handleExportMarkdown = () => {
    const blob = new Blob([summary], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${systemName.replace(/\s+/g, "-")}-design.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleExportPDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    const maxWidth = pageWidth - 2 * margin;
    let yPosition = margin;

    doc.setFontSize(20);
    doc.text(systemName, margin, yPosition);
    yPosition += 10;

    doc.setFontSize(12);

    if (nodes.length > 0) {
      yPosition += 10;
      if (yPosition > pageHeight - 30) {
        doc.addPage();
        yPosition = margin;
      }

      doc.setFontSize(14);
      doc.setFont(undefined, "bold");
      doc.text("Architecture Components", margin, yPosition);
      yPosition += 8;

      doc.setFontSize(11);
      doc.setFont(undefined, "normal");

      nodes.forEach((node) => {
        if (yPosition > pageHeight - 30) {
          doc.addPage();
          yPosition = margin;
        }
        doc.text(`• ${node.data.label}`, margin + 5, yPosition);
        yPosition += 7;
      });
    }

    if (edges.length > 0) {
      yPosition += 10;
      if (yPosition > pageHeight - 30) {
        doc.addPage();
        yPosition = margin;
      }

      doc.setFontSize(14);
      doc.setFont(undefined, "bold");
      doc.text("Component Connections", margin, yPosition);
      yPosition += 8;

      doc.setFontSize(11);
      doc.setFont(undefined, "normal");

      edges.forEach((edge) => {
        const sourceNode = nodes.find((n) => n.id === edge.source);
        const targetNode = nodes.find((n) => n.id === edge.target);
        if (sourceNode && targetNode) {
          if (yPosition > pageHeight - 30) {
            doc.addPage();
            yPosition = margin;
          }
          doc.text(
            `• ${sourceNode.data.label} → ${targetNode.data.label}`,
            margin + 5,
            yPosition
          );
          yPosition += 7;
        }
      });
    }

    doc.save(`${systemName.replace(/\s+/g, "-")}-design.pdf`);
  };

  return (
    <div className="flex min-h-screen">
      <Sidebar />
      <main className="flex-1 p-8 bg-gray-50">
        <div className="max-w-4xl mx-auto">
          <div className="flex items-center justify-between mb-8">
            <h1 className="text-3xl font-bold">Summary + Export</h1>
            <div className="flex gap-4">
              <button
                onClick={handleExportMarkdown}
                className="flex items-center gap-2 px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
              >
                <FiFileText className="w-5 h-5" />
                Export Markdown
              </button>
              <button
                onClick={handleExportPDF}
                className="flex items-center gap-2 px-6 py-3 bg-red-600 text-white rounded-lg hover:bg-red-700 transition-colors"
              >
                <FiDownload className="w-5 h-5" />
                Export PDF
              </button>
            </div>
          </div>

          <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-8">
            <div className="prose max-w-none">
              <h1 className="text-3xl font-bold mb-6">{systemName}</h1>

              <h2 className="text-2xl font-semibold mt-8 mb-4">
                System Overview
              </h2>
              <p className="text-gray-700 mb-6">
                This document outlines the system design for <strong>{systemName}</strong>.
              </p>

              {nodes.length > 0 && (
                <>
                  <h2 className="text-2xl font-semibold mt-8 mb-4">
                    Architecture Components
                  </h2>
                  <ul className="list-disc list-inside space-y-2 mb-6">
                    {nodes.map((node) => (
                      <li key={node.id} className="text-gray-700">
                        {node.data.label}
                      </li>
                    ))}
                  </ul>
                </>
              )}

              {edges.length > 0 && (
                <>
                  <h2 className="text-2xl font-semibold mt-8 mb-4">
                    Component Connections
                  </h2>
                  <ul className="list-disc list-inside space-y-2 mb-6">
                    {edges.map((edge) => {
                      const sourceNode = nodes.find((n) => n.id === edge.source);
                      const targetNode = nodes.find((n) => n.id === edge.target);
                      if (sourceNode && targetNode) {
                        return (
                          <li key={edge.id} className="text-gray-700">
                            {sourceNode.data.label} → {targetNode.data.label}
                          </li>
                        );
                      }
                      return null;
                    })}
                  </ul>
                </>
              )}
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
